---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: clickhouse
  labels:
    app: zookeeper
spec:
  ports:
    - port: 2181
      name: client
    - port: 7000
      name: prometheus
  selector:
    app: zookeeper
    what: node
