---
# Setup max number of unavailable pods in StatefulSet
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: zookeeper
  namespace: clickhouse
spec:
  selector:
    matchLabels:
      app: zookeeper
      what: node
  maxUnavailable: 1
