---
apiVersion: v1
kind: Service
metadata:
  name: fluent-bit
  namespace: fluent-bit
  labels:
    app: fluent-bit
spec:
  ports:
    - name: http-metrics
      port: 2020
      protocol: TCP
      targetPort: http-metrics
  selector:
    app: fluent-bit
  type: ClusterIP
