name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  go:
    name: Go
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
          cache: true
          cache-dependency-path: go.sum

      - name: Download Dependencies
        run: |
          go mod download

      - name: Vet
        run: |
          make vet

      - name: Test
        run: |
          make test

      - name: Build Plugin
        run: |
          make build-plugin

      - name: Build Ingester
        run: |
          make build-ingester
